### PR TITLE
Add populate_aap role

### PR DESCRIPTION
**Pull request by matoval**
# Description

Add populate_aap role

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

### CODE REVIEW

**Review by chadmf — COMMENTED** [review]
instead of having these each as individual vars you could maybe put them in a table like the containerized installer does, or even just a var example. It is good that we call out the required vars to make it easier for people to use.

**Comment by maxamillion** [comment]
I'd like to suggest we rename this to something along the lines of `load_content` and move it to https://github.com/redhat-cop/controller_configuration as a more general purpose Ansible Content loading utility. Thoughts? @matoval @chadmf

**Comment by matoval** [comment]
> I'd like to suggest we rename this to something along the lines of `load_content` and move it to https://github.com/redhat-cop/controller_configuration as a more general purpose Ansible Content loading utility. Thoughts? @matoval @chadmf

Sounds good to me! I'll move it and work on making it more general.

**Comment by maxamillion** [comment]
@matoval welllllll nevermind, I was completely mistaken. Disregard me, what you've done here is exactly what we need and the thing I thought we needed already exists .... :|

**Review by resoluteCoder — APPROVED** [review]

**Pull request merged**
