### PR TITLE
Add ignition to simplified installer blueprint

### PR DESCRIPTION
**Pull request by luisarizmendi**
# Description

We need to be able to include ignition definition for simplified installer images

### CODE REVIEW

**Review by ericzolf — COMMENTED** [review]
Looks mostly good to me, just wondering about a few things (which might be due to my lack of experience with this project):

1. shouldn't the new option be documented somewhere?
2. I don't see any blueprint import file option?

**Comment by luisarizmendi** [comment]
Thanks for reviewing

1. shouldn't the new option be documented somewhere?
Well, more than a new option I could say that it was some kind of BUG since you cannot customize the FDO image at all if it's not with ignition that we were filtering out

2. I don't see any blueprint import file option?
Sorry this comes from a previous PR where I forgot to increase the galaxy version, so the content was not "updated" in galaxy. This is the PR already accepted: https://github.com/redhat-cop/infra.osbuild/pull/357

**Comment by ericzolf** [comment]
Then approved!

**Comment by luisarizmendi** [comment]
@ericzolf Azure pipelines are failing and blocking the merge, but I suppose that's not related to the changes introduced in this PR, am I right?

**Comment by luisarizmendi** [comment]
@ericzolf  @maxamillion can you please look at why the PR was not merged after approval?  Do I need to change anything?

Thanks.

**Review by ericzolf — APPROVED** [review]
I thought I had already done it but let me approve (again).

**Comment by ericzolf** [comment]
The short answer is that I don't know, I thought I had approved but perhaps I haven't... Also I don't know if you see but many checks were not successful, though I doubt due to your changes.

**Pull request merged**
