### PR TITLE
warn if sshkey file is undefined, add user password for kickstart, update README

### PR DESCRIPTION
**Pull request by matoval**
Resolves issue #74 

warn if sshkey file is undefined
conditionally add sshkey to kickstart file if defined
conditionally add user password to kickstart file if defined
update README

### CODE REVIEW

**Comment by matoval** [comment]
@jjaswanson4 What do you think of this solution to issue #74 ?

**Comment by jjaswanson4** [comment]
LGTM!

I'd consider even going one step further: if a user isn't provided in any way, just assume "root" or "ansible" or something like that.

I realize this potentially means you could build a system that you can't log in to, but I'd prefer that over the automation just failing out.

**Comment by matoval** [comment]
> LGTM!
> 
> I'd consider even going one step further: if a user isn't provided in any way, just assume "root" or "ansible" or something like that.
> 
> I realize this potentially means you could build a system that you can't log in to, but I'd prefer that over the automation just failing out.

Since we have the user defined in the defaults wouldn't it default to that user?

**Comment by jjaswanson4** [comment]
> > LGTM!
> > I'd consider even going one step further: if a user isn't provided in any way, just assume "root" or "ansible" or something like that.
> > I realize this potentially means you could build a system that you can't log in to, but I'd prefer that over the automation just failing out.
> 
> Since we have the user defined in the defaults wouldn't it default to that user?

Oh you're right, I forgot we had that in defaults, then yes we should be good.

**Review by resoluteCoder — APPROVED** [review]

**Pull request merged**
