### PR TITLE
Add [[container]] section in generated blueprint to support embedded container images

### PR DESCRIPTION
**Pull request by luisarizmendi**
# Description
Add [[container]] section in generated blueprint to support embedded container images

Related to RFE https://github.com/redhat-cop/infra.osbuild/issues/331

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

## Checklist

- [x] Added changelog fragment
- [ ] Tests exist for affected features covering positive and negative scenarios

### CODE REVIEW

**Comment by lucamaf** [comment]
was this merged?

**Comment by luisarizmendi** [comment]
I'm not sure if it was even reviewed. I think I pushed twice this PR

@maxamillion, @thom-at-redhat, @de1987, @resoluteCoder, @matoval if you think this cannot be merged it would be great if you point why so we can fix it.

Thanks.

**Comment by claudiol** [comment]
Re-Opening this PR for further review.

**Review by claudiol — APPROVED** [review]
/lgtm
Reviewed code.  The CI failure will be fixed in another PR separate from this one.

**Pull request merged**
