### PR TITLE
fix: concatenate lists without embedding into an outer layer of list

### PR DESCRIPTION
**Pull request by jharmison-redhat**
Fixes: #307

# Description

Concatenate lists using the `+` operator without encapsulating with an outer layer of list, since the length of the sum of the lists is the most important characteristic

## Type of change

What is it?

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [x] Tests update
- [ ] Refactor

## Checklist

- [x] Added changelog fragment
- [x] Tests exist for affected features covering positive and negative scenarios

### CODE REVIEW

**Comment by jharmison-redhat** [comment]
Looks like the test on idempotency here is flaky, will need a bit to dig into the test suite you've built to figure out why

**Comment by jharmison-redhat** [comment]
Tests issues appear to be fixed, the test now actually checks whether the flag works or not.

@maxamillion @matoval please review and merge ASAP, this is blocking documented functionality that we could really use right now :)

I'm happy to fix any nits that come up quickly.

**Review by matoval — APPROVED** [review]
LGTM

**Comment by jharmison-redhat** [comment]
thanks 
image

**Pull request merged**
